package com.elanrif.springbootstarterkit.mapper;

import com.elanrif.springbootstarterkit.dto.AddressDto;
import com.elanrif.springbootstarterkit.entity.Address;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(componentModel = "spring")
public interface AddressMapper {

    /**
     * Converts an Address entity into an Address response DTO.
     *
     * The user's ID is extracted from the associated User entity
     * and mapped to the userId field of the response DTO.
     */
    @Mapping(target = "userId", source = "user.id")
    AddressDto.Response toResponse(Address address);

    /**
     * Creates a new Address entity from a CreateRequest DTO.
     *
     * The ID is ignored because it is generated by the database.
     * The User relationship is ignored because it is assigned
     * by the AddressService using the provided userId.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "user", ignore = true)
    Address toEntity(AddressDto.CreateRequest request);

    /**
     * Updates an existing Address entity from an UpdateRequest DTO.
     *
     * Null fields from the request are ignored, which allows
     * partial updates (PATCH) without overwriting existing values.
     *
     * The ID and User relationship are ignored because they must
     * never be changed through an address update request.
     */
    @BeanMapping(
            nullValuePropertyMappingStrategy =
                    NullValuePropertyMappingStrategy.IGNORE
    )
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "user", ignore = true)
    void updateFromRequest(
            AddressDto.UpdateRequest request,
            @MappingTarget Address entity
    );
}