package com.elanrif.springbootstarterkit.mapper;

import com.elanrif.springbootstarterkit.dto.AuthDto;
import com.elanrif.springbootstarterkit.entity.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring", uses = AddressMapper.class)
public interface AuthMapper {

    /**
     * Converts a User entity into an authentication response DTO.
     *
     * The AddressMapper is used automatically by MapStruct when
     * mapping address-related fields.
     */
    AuthDto.Response toResponse(User user);

    /**
     * Creates a new User entity from a registration request.
     *
     * The ID is ignored because it is generated by the database.
     *
     * The status and role are ignored because their values are
     * controlled by the application's business rules and must not
     * be provided directly by the client during registration.
     *
     * The password is ignored because it must be handled explicitly
     * by the authentication service, typically by hashing it with
     * a PasswordEncoder before saving the user.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "role", ignore = true)
    @Mapping(target = "password", ignore = true)
    User toEntity(AuthDto.RegisterRequest request);
}