package com.elanrif.springbootstarterkit.mapper;

import com.elanrif.springbootstarterkit.dto.CommentDto;
import com.elanrif.springbootstarterkit.entity.Comment;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = "spring", uses = {UserMapper.class})
public interface CommentMapper {

    /**
     * Converts a Comment entity into a lightweight summary DTO.
     *
     * The UserMapper is used by MapStruct to convert the comment author
     * into the corresponding user DTO.
     */
    @Mapping(target = "author", source = "author")
    CommentDto.Summary toSummary(Comment comment);

    /**
     * Converts a Comment entity into the complete response DTO.
     *
     * The post ID is extracted from the associated Post entity.
     * The UserMapper is used to map the comment author.
     */
    @Mapping(target = "postId", source = "post.id")
    @Mapping(target = "author", source = "author")
    CommentDto.Response toResponse(Comment comment);

    /**
     * Creates a new Comment entity from a creation request.
     *
     * The ID is ignored because it is generated by the database.
     *
     * The author and post relationships are ignored because they are
     * determined by the application context and business rules.
     * They must be assigned by the CommentService rather than being
     * directly controlled by the client.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "author", ignore = true)
    @Mapping(target = "post", ignore = true)
    Comment toEntity(CommentDto.CreateRequest request);

    /**
     * Updates an existing Comment entity from an update request.
     *
     * The ID, author and post relationships are ignored because they
     * must not be modified through a comment update operation.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "author", ignore = true)
    @Mapping(target = "post", ignore = true)
    void updateFromRequest(
            CommentDto.UpdateRequest request,
            @MappingTarget Comment entity
    );
}