package com.elanrif.springbootstarterkit.mapper;

import com.elanrif.springbootstarterkit.dto.CommentDto;
import com.elanrif.springbootstarterkit.dto.PostDto;
import com.elanrif.springbootstarterkit.entity.Post;
import com.elanrif.springbootstarterkit.util.PageResponse;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
        componentModel = "spring",
        uses = {UserMapper.class, CommentMapper.class}
)
public interface PostMapper {

    /**
     * Converts a Post entity into a lightweight summary DTO.
     *
     * The UserMapper is used to map the post author.
     * The comment count is calculated from the comments associated
     * with the post. A null collection is treated as an empty collection.
     */
    @Mapping(target = "author", source = "author")
    @Mapping(
            target = "commentCount",
            expression = "java(post.getComments() != null ? post.getComments().size() : 0)"
    )
    PostDto.Summary toSummary(Post post);

    /**
     * Converts a Post entity into the complete response DTO.
     *
     * The author is mapped using UserMapper.
     * The number of comments is calculated from the post's comments.
     */
    @Mapping(target = "author", source = "author")
    @Mapping(
            target = "commentSize",
            expression = "java(post.getComments() != null ? post.getComments().size() : 0)"
    )
    PostDto.Response toResponse(Post post);

    /**
     * Builds the response used when displaying a post together with
     * its paginated comments.
     *
     * The post author is mapped from the Post entity and the paginated
     * comments are provided separately by the service layer.
     *
     * This keeps comment pagination independent from the Post entity
     * and avoids loading the entire comments collection.
     */
    @Mapping(target = "author", source = "post.author")
    @Mapping(target = "comments", source = "comments")
    PostDto.CommentsResponse toCommentsResponse(
            Post post,
            PageResponse<CommentDto.Response> comments
    );

    /**
     * Creates a new Post entity from a creation request.
     *
     * The ID is ignored because it is generated by the database.
     *
     * The author is ignored because it must be determined by the
     * authenticated user in the service layer.
     *
     * The comments collection is ignored because comments are separate
     * resources and are not created together with the post.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "author", ignore = true)
    @Mapping(target = "comments", ignore = true)
    Post toEntity(PostDto.CreateRequest request);

    /**
     * Updates an existing Post entity from an update request.
     *
     * Null values are ignored so that this mapping behaves correctly
     * for PATCH operations: fields not provided by the client keep
     * their existing values.
     *
     * The author and comments are ignored because they are relationships
     * managed by the service layer and must not be modified through
     * a regular post update.
     */
    @BeanMapping(
            nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
    )
    @Mapping(target = "author", ignore = true)
    @Mapping(target = "comments", ignore = true)
    void updateFromRequest(
            PostDto.UpdateRequest request,
            @MappingTarget Post entity
    );
}