package com.elanrif.springbootstarterkit.mapper;

import com.elanrif.springbootstarterkit.dto.AddressDto;
import com.elanrif.springbootstarterkit.dto.UserDto;
import com.elanrif.springbootstarterkit.entity.User;
import com.elanrif.springbootstarterkit.util.PageResponse;
import org.mapstruct.*;

@Mapper(componentModel = "spring", uses = AddressMapper.class)
public interface UserMapper {

    UserDto.Summary toSummary(User user);

    /**
     * Converts a User entity into the complete response DTO.
     *
     * The number of addresses is calculated from the user's addresses
     * collection. A null collection is treated as an empty collection.
     *
     * Address mapping is delegated to AddressMapper.
     */
    @Mapping(
            target = "addrSize",
            expression = "java(user.getAddresses() != null ? user.getAddresses().size() : 0)"
    )
    UserDto.Response toResponse(User user);

    /**
     * Builds the response used when displaying a user together with
     * the user's paginated addresses.
     *
     * The paginated addresses are provided separately by the service layer.
     */
    @Mapping(target = "addresses", source = "addresses")
    UserDto.AddressesResponse toAddressesResponse(
            User user,
            PageResponse<AddressDto.Response> addresses
    );

    /**
     * Creates a new User entity from a creation request.
     *
     * The ID is ignored because it is generated by the database.
     */
    @Mapping(target = "id", ignore = true)
    User toEntity(UserDto.CreateRequest request);

    /**
     * Updates an existing User entity from an update request.
     *
     * Null values are ignored so that fields not provided during
     * a PATCH request keep their existing values.
     */
    @BeanMapping(
            nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
    )
    void updateFromRequest(
            UserDto.UpdateRequest request,
            @MappingTarget User entity
    );
}