
server:
  port: ${SERVER_PORT:8081} # Default to 8081 to avoid conflict with Keycloak on 8080
spring:
  application:
    name: springboot-starter-kit
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI}
          jwk-set-uri: ${KC_JWK_URL}

# Reset Token
nodemailer:
  reset-token:
    hmac: ${RESET_TOKEN_HMAC}
    secret: ${RESET_TOKEN_SECRET_KEY}

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

# Keycloak Configuration
keycloak:
  auth-server-url: ${KC_AUTH_SERVER_URL}
  realm: ${KC_REALM}
  client-id: ${KC_CLIENT_ID}
  client-secret: ${KC_CLIENT_SECRET}
  admin:
    client-id: ${KC_ADMIN_CLIENT_ID}
    username: ${KC_ADMIN_USERNAME}
    password: ${KC_ADMIN_PASSWORD}
