spring:
  jpa:
    hibernate:
      ddl-auto: update # TODO: use flyway for production

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.elanrif.springbootstarterkit: INFO
    org.hibernate.SQL: WARN
