
server:
  port: ${SERVER_PORT:8081} # Default to 8081 to avoid conflict with Keycloak on 8080
spring:
  application:
    name: ${SERVER_NAME:kickstart-springboot} # Default to kickstart-springboot if SERVER_NAME is not set
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  profiles:
    active:
      - ${ENV:local} # Default to dev profile if ENV is not set
  session:
    jdbc:
      initialize-schema: always
    timeout: 30m   # optionnel, durée de vie d'une session inactive

# Reset Token
nodemailer:
  reset-token:
    hmac: ${RESET_TOKEN_HMAC}
    secret: ${RESET_TOKEN_SECRET_KEY}

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
